### PR TITLE
bors: add appropriate configuration for it.

### PR DESCRIPTION
**Pull request by huonw**
Also, remove homu.

### CODE REVIEW

**Comment by autohuonw** [comment]
@huonw: no appropriate reviewer found, use r? to override

**Comment by huonw** [comment]
bors try

**Comment by huonw** [comment]
bors try

**Comment by notriddle** [comment]
@cuviper It didn't go through because "REVIEW REQUIRED: At least 2 approving reviews are required by reviewers with write access."

**Comment by cuviper** [comment]
@huonw Requiring **2** reviewers seems harsh when AFAIK you and I are the only ones with write access.  Or do the checks (like bors) count as a review?

**Comment by notriddle** [comment]
The bors checks don't count as a review. It counts as a status check.

Also, you probably want to add [`required_approvals`](https://bors.tech/documentation/) to the bors.toml, and turn this check off in GitHub, so that it gives you a real warning message instead of ragequitting with a 422 after it tries to push it to master.

**Comment by huonw** [comment]
bors r=cuviper

**Comment by huonw** [comment]
That works! 🎉

**Pull request merged**
