### PR TITLE
Added more asserts to documentation

### PR DESCRIPTION
**Pull request by wackywendell**
Never hurts to make sure the docs actually do what they say, right?

### CODE REVIEW

**Comment by huonw** [comment]
@autohuonw r+

**Comment by autohuonw** [comment]
:pushpin: Commit 534d0a4 has been approved by `huonw`

**Comment by autohuonw** [comment]
:hourglass: Testing commit 534d0a4 with merge a3372f5...

**Comment by autohuonw** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/huonw/primal/builds/66473072)

**Comment by huonw** [comment]
Thanks @wackywendell!

**Pull request merged**
