### PR TITLE
Update smallvec to 0.6

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by autohuonw** [comment]
Thanks for the pull request, and welcome! You should hear from @huonw (or someone else) soon.

**Comment by debris** [comment]
Is there any reason to keep this crate compatible with archaic 1.9?

**Comment by cuviper** [comment]
I try to be very conservative with changing rustc requirements on crates I maintain, but I think it wouldn't be a big deal to raise primal's.  Do you know what we'd have to increase to here?

There's also the dev-dependency on `time` held back to `<=0.1.37` for rust compatibility -- so if we can unhinder that too, all the better.

**Comment by cuviper** [comment]
Thanks!

**Pull request merged**
